### ISSUE TITLE
Issue Tracking CLI

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#101]
In an effort to allow for early dog-fooding we are trying to CLI more things.  As the development of issue tracking matures, we should add a CLI for interacting with it.

To list off some of the commands it should support:
- [ ] Create a new issue
- [ ] List all issues
- [ ] Reply to an issue's main thread
- [ ] Reply to a sub-thread of an issue
- [ ] React to a comment
- [ ] Add an assignee

The functionality of the ops will likely guide these commands, but they're listed here for inspiration :)
