### ISSUE TITLE
Signatures and verifications

### ISSUE THREAD

**Issue by massimiliano-mantione** [radicle-dev/radicle-link#87]
This is a meta-issue to track the steps to implement user and project identity and verification, key revocation, end item signatures and verification (like signing a comment in the issue tracker).

The goal is to avoid doing all the work in a single pull request but to have a single place to track the steps and discuss the high level choices driving the single pull requests.

The main concepts is that we have "entities" (for now users and project) that have a "top level identity".

Entities have the following properties:

* They can _evolve_ over time, so they have a sequence of _revisions_.
* Their _identity_ is stable (it does not change over time), and it is the hash of their initial revision.
* Each revision contains the hash of the previous revision, which is also hashed, so that the sequence of revisions is a Merkel tree (actually just a list).
* They can be signed, either with a key they _own_, or using a key belonging to a different entity (the _certifier_); note that when applying multiple signatures, signatures are not themselves signed (what is signed is always only the entity itself).
* Each revision specifies the set of owned keys and trusted certifiers.
* Each revision must be signed by all its owned keys and trusted certifiers.
* Each subsequent revision must be signed by a quorum of the previous keys and certifiers, to prove that the entity evolution is actually under the control of its current "owners" (the idea is taken from [TUF](https://theupdateframework.io)).

Note that in the case of projects the set of "owned keys" is empty.
Currently for users we don't have the concept of "certifiers" and the owned keys are the device keys.
It could be interesting to add the concept of "certifier" for a user (to represent a web of trust and to allow safe identity recovery even when losing a quorum of the owned keys) but this should be analyzed in a different issue.

To implement these concepts in radicle we should do these steps (not necessarily exactly in this order):

- [ ] Implement a framework to sign entities and verify their history (should be PR #85).
- [ ] Properly handle key revocation (with a subsequent PR evolving the code in #85, I would keep it separated because it has complexity of its own).
- [ ] Implement real resolvers for entities and their histories.
- [ ] Replace the current `meta::Project` and `meta::Contributor` with the structs defined in #85.
- [ ] Consolidate the use of text to represent small buffers (like hashes, keys and signatures), likely using [multibase](https://crates.io/crates/multibase).
- [ ] Use Blake2b-256 as hashing function as stated in #88.
- [ ] Unify the concept of signature "of something" (just the _hash_ should be signed) and "by some entity" (which could be the signed entity itself, one of the certifiers, or one of the certifiers of a given entity). This unification will allow using entities as ACLs for arbitrary operations.

When this is done (including key revocation and signature concept unification) we could build "item signatures" on top of it.
The idea is that individual artifacts authored (and owned) by a single user can be signed by that user, with a single key, and these signatures can be verified at any point in time.
This should be the base for signing operations in the issue tracker (and any future "applet").

Reasonable steps could be:

- [ ] Extract the "unified signature" data structure so that it can be embedded in any other item.
- [ ] Define a trait that exposes a hash and an owner, and the ability to sign it.
- [ ] Implement that trait for issue tracker operations.
